const COUNTRY_MAP: Record<string, string> = {
  alb: 'Albania',
  dza: 'Algeria',
  and: 'Andorra',
  ago: 'Angola',
  arg: 'Argentina',
  arm: 'Armenia',
  aus: 'Australia',
  aut: 'Austria',
  aze: 'Azerbaijan',
  bhs: 'Bahamas',
  bhr: 'Bahrain',
  bgd: 'Bangladesh',
  brb: 'Barbados',
  blr: 'Belarus',
  bel: 'Belgium',
  blz: 'Belize',
  ben: 'Benin',
  btn: 'Bhutan',
  bol: 'Bolivia',
  bih: 'Bosnia and Herzegovina',
  bwa: 'Botswana',
  bra: 'Brazil',
  brn: 'Brunei',
  bgr: 'Bulgaria',
  bfa: 'Burkina Faso',
  bdi: 'Burundi',
  khm: 'Cambodia',
  cmr: 'Cameroon',
  can: 'Canada',
  cpv: 'Cape Verde',
  caf: 'Central African Republic',
  tcd: 'Chad',
  chl: 'Chile',
  chn: 'China',
  col: 'Colombia',
  com: 'Comoros',
  cog: 'Congo',
  cod: 'Congo (DRC)',
  cri: 'Costa Rica',
  civ: "Côte d'Ivoire",
  hrv: 'Croatia',
  cub: 'Cuba',
  cyp: 'Cyprus',
  cze: 'Czech Republic',
  dnk: 'Denmark',
  dji: 'Djibouti',
  dma: 'Dominica',
  dom: 'Dominican Republic',
  ecu: 'Ecuador',
  egy: 'Egypt',
  slv: 'El Salvador',
  gnq: 'Equatorial Guinea',
  eri: 'Eritrea',
  est: 'Estonia',
  swz: 'Eswatini',
  eth: 'Ethiopia',
  fji: 'Fiji',
  fin: 'Finland',
  fra: 'France',
  gab: 'Gabon',
  gmb: 'Gambia',
  geo: 'Georgia',
  deu: 'Germany',
  gha: 'Ghana',
  grc: 'Greece',
  grd: 'Grenada',
  gtm: 'Guatemala',
  gin: 'Guinea',
  gnb: 'Guinea-Bissau',
  guy: 'Guyana',
  hti: 'Haiti',
  hnd: 'Honduras',
  hun: 'Hungary',
  isl: 'Iceland',
  ind: 'India',
  idn: 'Indonesia',
  irn: 'Iran',
  irq: 'Iraq',
  irl: 'Ireland',
  isr: 'Israel',
  ita: 'Italy',
  jam: 'Jamaica',
  jpn: 'Japan',
  jor: 'Jordan',
  kaz: 'Kazakhstan',
  ken: 'Kenya',
  kir: 'Kiribati',
  kwt: 'Kuwait',
  kgz: 'Kyrgyzstan',
  lao: 'Laos',
  lva: 'Latvia',
  lbn: 'Lebanon',
  lso: 'Lesotho',
  lbr: 'Liberia',
  lby: 'Libya',
  lie: 'Liechtenstein',
  ltu: 'Lithuania',
  lux: 'Luxembourg',
  mdg: 'Madagascar',
  mwi: 'Malawi',
  mys: 'Malaysia',
  mdv: 'Maldives',
  mli: 'Mali',
  mlt: 'Malta',
  mhl: 'Marshall Islands',
  mrt: 'Mauritania',
  mus: 'Mauritius',
  mex: 'Mexico',
  fsm: 'Micronesia',
  mda: 'Moldova',
  mco: 'Monaco',
  mng: 'Mongolia',
  mne: 'Montenegro',
  mar: 'Morocco',
  moz: 'Mozambique',
  mmr: 'Myanmar',
  nam: 'Namibia',
  nru: 'Nauru',
  npl: 'Nepal',
  nld: 'Netherlands',
  nzl: 'New Zealand',
  nic: 'Nicaragua',
  ner: 'Niger',
  nga: 'Nigeria',
  mkd: 'North Macedonia',
  nor: 'Norway',
  omn: 'Oman',
  pak: 'Pakistan',
  plw: 'Palau',
  pan: 'Panama',
  png: 'Papua New Guinea',
  pry: 'Paraguay',
  per: 'Peru',
  phl: 'Philippines',
  pol: 'Poland',
  prt: 'Portugal',
  qat: 'Qatar',
  rou: 'Romania',
  rus: 'Russian Federation',
  rwa: 'Rwanda',
  kna: 'Saint Kitts and Nevis',
  lca: 'Saint Lucia',
  vct: 'Saint Vincent and the Grenadines',
  wsm: 'Samoa',
  smr: 'San Marino',
  stp: 'Sao Tome and Principe',
  sau: 'Saudi Arabia',
  sen: 'Senegal',
  srb: 'Serbia',
  syc: 'Seychelles',
  sle: 'Sierra Leone',
  sgp: 'Singapore',
  svk: 'Slovakia',
  svn: 'Slovenia',
  slb: 'Solomon Islands',
  som: 'Somalia',
  zaf: 'South Africa',
  kor: 'South Korea',
  ssd: 'South Sudan',
  esp: 'Spain',
  lka: 'Sri Lanka',
  sdn: 'Sudan',
  sur: 'Suriname',
  swe: 'Sweden',
  che: 'Switzerland',
  syr: 'Syria',
  twn: 'Taiwan',
  tjk: 'Tajikistan',
  tza: 'Tanzania',
  tha: 'Thailand',
  tls: 'Timor-Leste',
  tgo: 'Togo',
  ton: 'Tonga',
  tto: 'Trinidad and Tobago',
  tun: 'Tunisia',
  tur: 'Turkey',
  tkm: 'Turkmenistan',
  tuv: 'Tuvalu',
  uga: 'Uganda',
  ukr: 'Ukraine',
  are: 'United Arab Emirates',
  gbr: 'United Kingdom',
  usa: 'United States',
  ury: 'Uruguay',
  uzb: 'Uzbekistan',
  vut: 'Vanuatu',
  vat: 'Vatican City',
  ven: 'Venezuela',
  vnm: 'Vietnam',
  yem: 'Yemen',
  zmb: 'Zambia',
  zwe: 'Zimbabwe',
};

export function countryName(code: string) {
  const normalized = code.trim().toLowerCase();
  return COUNTRY_MAP[normalized] || code.toUpperCase();
}