const COUNTRY_MAP: Record<string, string> = {
  aus: 'Australia',
  aut: 'Austria',
  are: 'United Arab Emirates',
  alb: 'Albania',
  arg: 'Argentina',
  bel: 'Belgium',
  bgr: 'Bulgaria',
  bra: 'Brazil',
  can: 'Canada',
  che: 'Switzerland',
  chl: 'Chile',
  col: 'Colombia',
  cze: 'Czech Republic',
  deu: 'Germany',
  dnk: 'Denmark',
  esp: 'Spain',
  est: 'Estonia',
  fin: 'Finland',
  fra: 'France',
  gbr: 'United Kingdom',
  gha: 'Ghana',
  grc: 'Greece',
  hrv: 'Croatia',
  hun: 'Hungary',
  idn: 'Indonesia',
  ind: 'India',
  irl: 'Ireland',
  ita: 'Italy',
  jpn: 'Japan',
  ken: 'Kenya',
  kaz: 'Kazakhstan',
  lka: 'Sri Lanka',
  ltu: 'Lithuania',
  lva: 'Latvia',
  mda: 'Moldova',
  mex: 'Mexico',
  mys: 'Malaysia',
  nld: 'Netherlands',
  nor: 'Norway',
  nzl: 'New Zealand',
  pak: 'Pakistan',
  per: 'Peru',
  phl: 'Philippines',
  pol: 'Poland',
  prt: 'Portugal',
  rou: 'Romania',
  rus: 'Russian Federation',
  srb: 'Serbia',
  svk: 'Slovakia',
  svn: 'Slovenia',
  swe: 'Sweden',
  tha: 'Thailand',
  tur: 'Turkey',
  ukr: 'Ukraine',
  usa: 'United States',
  uzb: 'Uzbekistan',
  zaf: 'South Africa',
  zmb: 'Zambia',
  egy: 'Egypt',
};

export function countryName(code: string) {
  const normalized = code.trim().toLowerCase();
  return COUNTRY_MAP[normalized] || code.toUpperCase();
}