const ISO3_TO_NAME: Record<string, string> = {
  aus: 'Australia',
  mys: 'Malaysia',
  usa: 'United States',
  ukr: 'Ukraine',
  are: 'United Arab Emirates',
  bel: 'Belgium',
  che: 'Switzerland',
  mda: 'Moldova',
  rus: 'Russian Federation',
  alb: 'Albania',
  ind: 'India',
  gha: 'Ghana',
  egy: 'Egypt',
  zaf: 'South Africa',
  zmb: 'Zambia',
  ken: 'Kenya',
  pak: 'Pakistan',
  idn: 'Indonesia',
  gbr: 'United Kingdom',
  can: 'Canada',
  deu: 'Germany',
  fra: 'France',
  ita: 'Italy',
  esp: 'Spain',
  pol: 'Poland',
  bra: 'Brazil',
  mex: 'Mexico',
  arg: 'Argentina',
  chl: 'Chile',
  per: 'Peru',
  nzl: 'New Zealand',
  tur: 'Turkey',
  kaz: 'Kazakhstan',
  nld: 'Netherlands',
  aut: 'Austria',
  cze: 'Czechia',
  svk: 'Slovakia',
  hun: 'Hungary',
  rou: 'Romania',
  bgr: 'Bulgaria',
  prt: 'Portugal',
  swe: 'Sweden',
  nor: 'Norway',
  dnk: 'Denmark',
  fin: 'Finland',
  irl: 'Ireland',
  jpn: 'Japan',
  kor: 'South Korea',
  vnm: 'Vietnam',
  phl: 'Philippines',
  tha: 'Thailand',
  sau: 'Saudi Arabia',
  qat: 'Qatar',
  kwt: 'Kuwait',
  omn: 'Oman',
  irq: 'Iraq',
  irn: 'Iran',
  geo: 'Georgia',
  arm: 'Armenia',
  aze: 'Azerbaijan',
  uzb: 'Uzbekistan',
  kgz: 'Kyrgyzstan',
  tkm: 'Turkmenistan',
  lva: 'Latvia',
  est: 'Estonia',
  ltu: 'Lithuania',
  svn: 'Slovenia',
  hrv: 'Croatia',
  srb: 'Serbia',
  bih: 'Bosnia and Herzegovina',
  mkd: 'North Macedonia',
  grc: 'Greece',
  mar: 'Morocco',
  tun: 'Tunisia',
  dza: 'Algeria',
  nga: 'Nigeria',
  eth: 'Ethiopia',
  uga: 'Uganda',
  tza: 'Tanzania',
  col: 'Colombia',
  ury: 'Uruguay',
  bol: 'Bolivia',
  ecu: 'Ecuador',
  ven: 'Venezuela',
  pan: 'Panama',
  cri: 'Costa Rica',
  gtm: 'Guatemala',
  dom: 'Dominican Republic',
  pri: 'Puerto Rico',
};

export function countryName(code: string): string {
  const normalized = (code || '').trim().toLowerCase();
  if (!normalized) return 'Unknown';
  if (ISO3_TO_NAME[normalized]) return ISO3_TO_NAME[normalized];

  try {
    const region = normalized.length === 2 ? normalized.toUpperCase() : normalized;
    const display = new Intl.DisplayNames(['en'], { type: 'region' }).of(region.toUpperCase());
    if (display) return display;
  } catch {}

  return normalized.toUpperCase();
}
